// src/lib/Hero.svelte
<script lang="ts">
  import { i18n } from './i18n.svelte';
  import { Button } from './components/ui/button';
  import { Badge } from './components/ui/badge';
  import DownloadSimple from 'phosphor-svelte/lib/DownloadSimple';
  import GithubLogo from 'phosphor-svelte/lib/GithubLogo';

  let visible = $state(false);
  
  $effect(() => {
    const timer = setTimeout(() => {
      visible = true;
    }, 100);
    return () => clearTimeout(timer);
  });
</script>

<section class="relative min-h-screen flex flex-col items-center justify-center py-24 px-4 overflow-hidden" id="hero">
  <!-- Background -->
  <div class="absolute inset-0 overflow-hidden pointer-events-none">
    <div class="absolute w-[600px] h-[600px] rounded-full blur-[100px] opacity-50 bg-red-500/25 -top-[200px] -right-[100px] animate-pulse"></div>
    <div class="absolute w-[400px] h-[400px] rounded-full blur-[100px] opacity-50 bg-blue-500/20 -bottom-[100px] -left-[100px] animate-pulse"></div>
    <div class="absolute w-[300px] h-[300px] rounded-full blur-[100px] opacity-50 bg-orange-500/15 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse"></div>
    <div class="absolute inset-0 bg-[linear-gradient(rgba(238,44,11,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(238,44,11,0.03)_1px,transparent_1px)] bg-[size:60px_60px] [mask-image:radial-gradient(ellipse_at_center,black_0%,transparent_70%)]"></div>
  </div>
  
  <!-- Content -->
  <div 
    class="text-center z-10 max-w-4xl mx-auto transition-all duration-700 ease-out {visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}"
  >
    <Badge variant="outline" class="mb-6 gap-2 px-4 py-1.5 text-sm">
      <span class="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
      {i18n.t.hero.badge}
    </Badge>
    
    <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight tracking-tight">
      {i18n.t.hero.title}<br class="md:hidden" />
      <span class="brand-gradient">{i18n.t.hero.titleGlow}</span>
    </h1>
    
    <p class="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-8 leading-relaxed">
      {i18n.t.hero.description}
    </p>
    
    <div class="flex gap-4 justify-center flex-wrap mb-12">
      <Button href="#download" size="lg" class="gap-2">
        <DownloadSimple size={20} weight="bold" />
        {i18n.t.hero.ctaDownload}
      </Button>
      <Button href="https://github.com/FerrisMind/Oxide-Lab" variant="outline" size="lg" class="gap-2">
        <GithubLogo size={20} weight="fill" />
        {i18n.t.hero.ctaGithub}
      </Button>
    </div>
  </div>
  
  <!-- App Screenshot -->
  <div 
    class="relative mt-16 z-10 transition-all duration-1000 ease-out delay-300 {visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-12'}"
  >
    <div class="absolute -inset-12 bg-gradient-radial from-red-500/20 to-transparent pointer-events-none"></div>
    <div class="relative bg-card/95 border border-border rounded-4xl overflow-hidden shadow-2xl max-w-[1128px] w-[90vw]">
      <div class="bg-background">
        <img 
          src="https://raw.githubusercontent.com/FerrisMind/Oxide-Lab/main/.github/assets/screenshots/chat-dark.png" 
          alt="Oxide Lab Interface" 
          class="w-full h-auto block"
        />
      </div>
    </div>
  </div>
</section>

// src/components/landing/hero.tsx
"use client";

import { Button } from "@/components/ui/button";
import { useState, useEffect, CSSProperties } from "react";
import { useLanguage } from "@/contexts/language-context";
import {
  AppleLogo,
  WindowsLogo,
  LinuxLogo,
  Cpu,
  GraphicsCard,
  MagnifyingGlass,
  X,
  RocketLaunch,
  Rocket,
} from "@phosphor-icons/react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

type ParticleStyle = {
  duration: number;
  delay: number;
  size: number;
  startX: number;
  startY: number;
};

const Particle = () => {
  const [style, setStyle] = useState<ParticleStyle | null>(null);

  useEffect(() => {
    setStyle({
      duration: Math.random() * 5 + 5,
      delay: Math.random() * 5,
      size: Math.random() * 4 + 2,
      startX: Math.random() * 80 + 10,
      startY: Math.random() * 20 - 10,
    });
  }, []);

  if (!style) {
    return null;
  }

  const particleStyles: CSSProperties = {
    width: `${style.size}px`,
    height: `${style.size}px`,
    left: `${style.startX}%`,
    top: `${style.startY}%`,
    animation: `particle-flow ${style.duration}s linear ${style.delay}s infinite`,
    boxShadow: "0 0 8px hsl(var(--accent) / 0.7)",
  };

  return (
    <div
      className="absolute rounded-full bg-gradient-accent opacity-0"
      style={particleStyles}
    />
  );
};

export default function HeroSection() {
  const { t, language } = useLanguage();
  const title = t("hero.title");
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isMagnifierOpen, setIsMagnifierOpen] = useState(false);

  return (
    <section
      id="hero"
      className="relative w-full h-screen min-h-[600px] md:min-h-[700px] flex items-center justify-center overflow-hidden"
    >
      <div className="absolute inset-0 bg-primary z-0">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,_rgba(255,255,255,0.05)_0%,_rgba(255,255,255,0)_60%)]"></div>
      </div>
      <div className="container relative z-10 mx-auto px-4 py-4 md:py-0 text-primary-foreground flex items-center min-h-screen">
        <div className="grid md:grid-cols-[2fr_3fr] gap-8 md:gap-8 items-center">
          <div className="text-left max-w-md">
            <h1 className="text-3xl sm:text-4xl md:text-6xl font-bold tracking-tighter leading-tight whitespace-pre-line">
              {title
                .replace("🚀", "")
                .split("\n")
                .map((line, index) => (
                  <span key={index}>
                    {index === 0 ? (
                      <>
                        <span className="font-bold">{line}</span>
                        <RocketLaunch
                          className="inline-block h-8 w-8 sm:h-10 sm:w-10 md:h-12 md:w-12 text-accent ml-2"
                          weight="fill"
                        />
                      </>
                    ) : (
                      <span className="text-xl sm:text-2xl md:text-3xl font-normal italic text-primary-foreground/80">
                        {line}
                      </span>
                    )}
                    {index < title.replace("🚀", "").split("\n").length - 1 && (
                      <br />
                    )}
                  </span>
                ))}
            </h1>
            <p className="mt-8 md:mt-24 text-base sm:text-lg md:text-xl max-w-lg text-primary-foreground/80">
              {t("hero.subtitle")}
            </p>
            <div className="mt-6 md:mt-8 flex flex-col sm:flex-row items-start sm:items-center gap-3 md:gap-4">
              <div className="flex flex-col">
                <DropdownMenu onOpenChange={setIsMenuOpen} modal={false}>
                  <DropdownMenuTrigger asChild>
                    <Button
                      size="lg"
                      className={cn(
                        "bg-gradient-accent text-[#1a1b39] rounded-xl px-6 shadow-lg hover:shadow-accent/50 transition-all",
                        isMenuOpen && "opacity-75"
                      )}
                    >
                      <WindowsLogo weight="light" className="h-6 w-6" />
                      <span>{t("hero.buttons.downloadWindows")}</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent className="w-[--radix-dropdown-menu-trigger-width]">
                    <DropdownMenuItem>
                      <Cpu className="mr-2 h-5 w-5" weight="light" />
                      <span>{t("hero.dropdown.cpuOnly")}</span>
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <div className="flex items-center mr-2">
                        <Cpu className="h-5 w-5" weight="light" />
                        <span className="mx-1">+</span>
                        <GraphicsCard className="h-5 w-5" weight="light" />
                      </div>
                      <span>{t("hero.dropdown.cpuGpu")}</span>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                <p className="mt-2 text-xs text-primary-foreground/60 text-center">
                  {t("hero.buttons.versionInfo")}
                </p>
              </div>

              <Button
                size="lg"
                variant="outline"
                className="bg-transparent text-primary-foreground/70 border-primary-foreground/30 hover:bg-primary-foreground/10 hover:text-primary-foreground rounded-xl px-6"
                disabled
              >
                <AppleLogo weight="light" className="h-6 w-6" />
                <span>{t("hero.buttons.comingSoonMacOS")}</span>
              </Button>
              <Button
                size="lg"
                variant="outline"
                className="bg-transparent text-primary-foreground/70 border-primary-foreground/30 hover:bg-primary-foreground/10 hover:text-primary-foreground rounded-xl px-6"
                disabled
              >
                <LinuxLogo weight="light" className="h-6 w-6" />
                <span>{t("hero.buttons.comingSoonLinux")}</span>
              </Button>
            </div>
          </div>
          <div className="hidden xl:flex items-center justify-end mr-[-90%]">
            <Dialog open={isMagnifierOpen} onOpenChange={setIsMagnifierOpen}>
              <DialogTrigger asChild>
                <div className="relative group cursor-pointer">
                  <img
                    src={`/static/screen1_${language}.png`}
                    alt="Oxide Lab Application Screenshot"
                    className="rounded-[12px] bg-background/20 backdrop-blur-sm shadow-2xl transition-transform group-hover:scale-105 w-full max-w-2xl scale-125"
                  />
                  <div className="absolute inset-0 bg-black/20 rounded-[12px] opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <MagnifyingGlass
                      className="h-8 w-8 text-white"
                      weight="bold"
                    />
                  </div>
                </div>
              </DialogTrigger>
              <DialogContent className="max-w-4xl w-full p-0 bg-transparent border-none">
                <DialogTitle className="sr-only">
                  Увеличенное изображение приложения Oxide Lab
                </DialogTitle>
                <div className="relative">
                  <img
                    src={`/static/screen1_${language}.png`}
                    alt="Oxide Lab Application Screenshot - Увеличенное изображение"
                    className="w-full h-auto rounded-lg shadow-2xl"
                  />
                  <button
                    onClick={() => setIsMagnifierOpen(false)}
                    className="absolute top-4 right-4 bg-black/50 hover:bg-black/70 text-white rounded-full p-2 transition-colors"
                  >
                    <X className="h-6 w-6" />
                  </button>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </div>
    </section>
  );
}
